# Generated by Django 3.1.3 on 2023-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='closing_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
