# Generated by Django 3.1.3 on 2023-08-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_app', '0002_election_closing_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='is_checked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='is_voting_open',
            field=models.BooleanField(default=False),
        ),
    ]
